#!/usr/bin/env python3
"""Preprocessing script for data/raw/2026_kumamoto_earthquake/extracted/road_restrictions.csv
Output: data/processed/road_restrictions_preprocessed.parquet

Generated by data-preprocessing skill.
"""
from __future__ import annotations

import json

import pandas as pd
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]  # project root

src = ROOT / "data/raw/2026_kumamoto_earthquake/extracted/road_restrictions.csv"
dst = ROOT / "data/processed/road_restrictions_preprocessed.parquet"


def validate_geometry_json(value: object) -> object:
    """Keep valid GeoJSON geometry objects and mark malformed values missing."""
    if pd.isna(value):
        return pd.NA
    try:
        parsed = json.loads(str(value))
    except (TypeError, ValueError, json.JSONDecodeError):
        return pd.NA
    return value if isinstance(parsed, dict) and "type" in parsed else pd.NA

# --- Load ---
df = pd.read_csv(src, encoding="utf-8-sig", low_memory=False)

# --- Select and rename columns ---
rename_map = {
    "snapshot_time": "Snapshot Time",
    "feature_index": "Feature Index",
    "\u770c\u540d": "Prefecture Name",
    "\u5e02\u753a\u6751\u540d": "Municipality Name",
    "\u9053\u8def\u7a2e\u5225": "Road Type",
    "\u8def\u7dda\u540d": "Route Name",
    "\u59cb\u70b9\u4f4f\u6240": "Start Address",
    "\u7d42\u70b9\u4f4f\u6240": "End Address",
    "\u898f\u5236\u7a2e\u5225": "Restriction Type",
    "\u898f\u5236\u7406\u7531": "Restriction Reason",
    "\u898f\u5236\u958b\u59cb_\u65e5\u6642": "Restriction Start Time",
    "\u898f\u5236\u958b\u59cb_\u5185\u5bb9": "Restriction Start Status",
    "\u5ef6\u9577_Km": "Affected Length (km)",
    "geometry_type": "Geometry Type",
    "geometry_json": "Geometry JSON",
    "source_url": "Source URL",
    "source_file": "Source File",
    "source_retrieved_at_utc": "Source Retrieved At UTC",
    "name": "Restriction Record Name",
    "\u59cb\u70b9": "Start Point Name",
    "\u7d42\u70b9": "End Point Name",
    "\u898f\u5236\u5185\u5bb9": "Restriction Status",
    "\u898f\u5236\u65b9\u5411": "Restriction Direction",
    "\u898f\u5236\u5ef6\u9577_Km": "Restricted Length (km)",
    "\u5730\u6574\u756a\u53f7": "Regional Bureau Code",
    "\u6574\u5099\u5c40\u540d": "Regional Bureau Name",
    "\u770c\u756a\u53f7": "Prefecture Code",
    "\u898f\u5236\u5909\u66f4_\u65e5\u6642": "Restriction Change Time",
    "\u898f\u5236\u5909\u66f4_\u5185\u5bb9": "Restriction Change Status",
    "\u8fc2\u56de\u8def_\u6709\u7121": "Detour Available",
    "\u5b64\u7acb\u96c6\u843d_\u6709\u7121": "Isolated Settlement Present",
    "\u4eba\u8eab_\u6709\u7121": "Personal Injury Present",
    "\u7269\u640d_\u6709\u7121": "Property Damage Present",
    "\u505c\u96fb_\u6709\u7121": "Power Outage Present",
}
df = df[list(rename_map.keys())].rename(columns=rename_map)

# --- Variable-level preprocessing ---
# Snapshot Time
df["Snapshot Time"] = pd.to_datetime(
    df["Snapshot Time"], errors="coerce", utc=True
).dt.tz_convert("Asia/Tokyo")
# Feature Index
df["Feature Index"] = pd.to_numeric(df["Feature Index"], errors="coerce")
df["Feature Index"] = df["Feature Index"].astype("Int64")
# Prefecture Name
df["Prefecture Name"] = df["Prefecture Name"].str.strip()
df["Prefecture Name"] = df["Prefecture Name"].astype("category")
# Municipality Name
df["Municipality Name"] = df["Municipality Name"].str.strip()
df["Municipality Name"] = df["Municipality Name"].astype("category")
# Road Type
df["Road Type"] = df["Road Type"].str.strip()
df["Road Type"] = df["Road Type"].astype("category")
# Route Name
df["Route Name"] = df["Route Name"].str.strip()
# Start Address
df["Start Address"] = df["Start Address"].str.strip()
# End Address
df["End Address"] = df["End Address"].str.strip()
# Restriction Type
df["Restriction Type"] = df["Restriction Type"].str.strip()
df["Restriction Type"] = df["Restriction Type"].astype("category")
# Restriction Reason
df["Restriction Reason"] = df["Restriction Reason"].str.strip()
df["Restriction Reason"] = df["Restriction Reason"].astype("category")
# Restriction Start Time
df["Restriction Start Time"] = pd.to_datetime(
    df["Restriction Start Time"], format="mixed", errors="coerce"
).dt.tz_localize("Asia/Tokyo", ambiguous="NaT", nonexistent="NaT")
# Restriction Start Status
df["Restriction Start Status"] = df["Restriction Start Status"].str.strip()
df["Restriction Start Status"] = df["Restriction Start Status"].astype("category")
# Affected Length (km)
df["Affected Length (km)"] = pd.to_numeric(df["Affected Length (km)"], errors="coerce")
df["Affected Length (km)"] = df["Affected Length (km)"].astype("Float64")
# Geometry Type
df["Geometry Type"] = df["Geometry Type"].str.strip()
df["Geometry Type"] = df["Geometry Type"].astype("category")
# Geometry JSON
df["Geometry JSON"] = df["Geometry JSON"].str.strip()
df["Geometry JSON"] = df["Geometry JSON"].map(validate_geometry_json)
# Source URL
df["Source URL"] = df["Source URL"].str.strip()
# Source File
df["Source File"] = df["Source File"].str.strip()
# Source Retrieved At UTC
df["Source Retrieved At UTC"] = pd.to_datetime(
    df["Source Retrieved At UTC"], errors="coerce", utc=True
)
# Restriction Record Name
df["Restriction Record Name"] = df["Restriction Record Name"].str.strip()
# Start Point Name
df["Start Point Name"] = df["Start Point Name"].str.strip()
# End Point Name
df["End Point Name"] = df["End Point Name"].str.strip()
# Restriction Status
df["Restriction Status"] = df["Restriction Status"].str.strip()
df["Restriction Status"] = df["Restriction Status"].astype("category")
# Restriction Direction
df["Restriction Direction"] = df["Restriction Direction"].str.strip()
df["Restriction Direction"] = df["Restriction Direction"].astype("category")
# Restricted Length (km)
df["Restricted Length (km)"] = pd.to_numeric(df["Restricted Length (km)"], errors="coerce")
df["Restricted Length (km)"] = df["Restricted Length (km)"].astype("Float64")
# Regional Bureau Code
df["Regional Bureau Code"] = pd.to_numeric(df["Regional Bureau Code"], errors="coerce")
df["Regional Bureau Code"] = df["Regional Bureau Code"].astype("Int64")
# Regional Bureau Name
df["Regional Bureau Name"] = df["Regional Bureau Name"].str.strip()
df["Regional Bureau Name"] = df["Regional Bureau Name"].astype("category")
# Prefecture Code
df["Prefecture Code"] = pd.to_numeric(df["Prefecture Code"], errors="coerce")
df["Prefecture Code"] = df["Prefecture Code"].astype("Int64")
# Restriction Change Time
df["Restriction Change Time"] = pd.to_datetime(
    df["Restriction Change Time"], format="mixed", errors="coerce"
).dt.tz_localize("Asia/Tokyo", ambiguous="NaT", nonexistent="NaT")
# Restriction Change Status
df["Restriction Change Status"] = df["Restriction Change Status"].str.strip()
df["Restriction Change Status"] = df["Restriction Change Status"].astype("category")
# Detour Available
df["Detour Available"] = df["Detour Available"].str.strip()
df["Detour Available"] = df["Detour Available"].map({"有": True, "無": False}).astype("boolean")
# Isolated Settlement Present
df["Isolated Settlement Present"] = df["Isolated Settlement Present"].str.strip()
df["Isolated Settlement Present"] = df["Isolated Settlement Present"].map(
    {"有": True, "無": False}
).astype("boolean")
# Personal Injury Present
df["Personal Injury Present"] = df["Personal Injury Present"].str.strip()
df["Personal Injury Present"] = df["Personal Injury Present"].map(
    {"有": True, "無": False}
).astype("boolean")
# Property Damage Present
df["Property Damage Present"] = df["Property Damage Present"].str.strip()
df["Property Damage Present"] = df["Property Damage Present"].map(
    {"有": True, "無": False}
).astype("boolean")
# Power Outage Present
df["Power Outage Present"] = df["Power Outage Present"].str.strip()
df["Power Outage Present"] = df["Power Outage Present"].map(
    {"有": True, "無": False}
).astype("boolean")

# --- Save ---
dst.parent.mkdir(parents=True, exist_ok=True)
df.to_parquet(dst, index=False, engine="pyarrow")
print(f"Saved {len(df):,} rows × {len(df.columns)} cols → {dst.relative_to(ROOT)}")
