#!/usr/bin/env python3
"""Preprocessing script for data/raw/2026_kumamoto_earthquake/extracted/emergency_water_points.csv
Output: data/processed/emergency_water_points_preprocessed.parquet

Generated by data-preprocessing skill.
"""
from __future__ import annotations

import re
import unicodedata

import pandas as pd
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]  # project root

src = ROOT / "data/raw/2026_kumamoto_earthquake/extracted/emergency_water_points.csv"
dst = ROOT / "data/processed/emergency_water_points_preprocessed.parquet"
facility_reference = (
    ROOT.parent
    / "KE01b/data/processed/kumamoto_evacuation_facilities_2012_preprocessed.parquet"
)


def normalize_facility_name(value: object) -> str:
    """Normalize Japanese facility names without applying fuzzy matching."""
    normalized = unicodedata.normalize("NFKC", str(value))
    normalized = re.sub(r"[\s　・･()（）]", "", normalized)
    return normalized.replace("コミセン", "コミュニティセンター")

# --- Load ---
df = pd.read_csv(src, encoding="utf-8-sig", low_memory=False)

# --- Select and rename columns ---
rename_map = {
    "municipality": "Municipality",
    "water_point_name": "Water Point Name",
    "valid_from_date": "Valid From Date",
    "valid_to_date": "Valid To Date",
    "opening_time": "Opening Time",
    "closing_time": "Closing Time",
    "allocation_basis": "Allocation Basis",
    "allocation_limit_liters": "Allocation Limit (L)",
    "water_type": "Water Type",
    "source_status_time": "Source Status Time",
    "source_url": "Source URL",
    "source_file": "Source File",
    "source_retrieved_at_utc": "Source Retrieved At UTC",
    "latitude": "Latitude",
    "longitude": "Longitude",
    "location_resolution_status": "Location Resolution Status",
}
df = df[list(rename_map.keys())].rename(columns=rename_map)

# --- Variable-level preprocessing ---
# Municipality
df["Municipality"] = df["Municipality"].str.strip()
df["Municipality"] = df["Municipality"].astype("category")
# Water Point Name
df["Water Point Name"] = df["Water Point Name"].str.strip()
# Valid From Date
df["Valid From Date"] = pd.to_datetime(df["Valid From Date"], format="%Y-%m-%d", errors="coerce")
# Valid To Date
df["Valid To Date"] = pd.to_datetime(df["Valid To Date"], format="%Y-%m-%d", errors="coerce")
# Opening Time
df["Opening Time"] = df["Opening Time"].str.strip()
# Closing Time
df["Closing Time"] = df["Closing Time"].str.strip()
# Allocation Basis
df["Allocation Basis"] = df["Allocation Basis"].str.strip()
df["Allocation Basis"] = df["Allocation Basis"].astype("category")
# Allocation Limit (L)
df["Allocation Limit (L)"] = pd.to_numeric(df["Allocation Limit (L)"], errors="coerce")
df["Allocation Limit (L)"] = df["Allocation Limit (L)"].astype("Float64")
# Water Type
df["Water Type"] = df["Water Type"].str.strip()
df["Water Type"] = df["Water Type"].astype("category")
# Source Status Time
df["Source Status Time"] = pd.to_datetime(
    df["Source Status Time"], errors="coerce", utc=True
).dt.tz_convert("Asia/Tokyo")
# Source URL
df["Source URL"] = df["Source URL"].str.strip()
# Source File
df["Source File"] = df["Source File"].str.strip()
# Source Retrieved At UTC
df["Source Retrieved At UTC"] = pd.to_datetime(
    df["Source Retrieved At UTC"], errors="coerce", utc=True
)
# Latitude
df["Latitude"] = pd.to_numeric(df["Latitude"], errors="coerce")
df["Latitude"] = df["Latitude"].astype("Float64")
# Longitude
df["Longitude"] = pd.to_numeric(df["Longitude"], errors="coerce")
df["Longitude"] = df["Longitude"].astype("Float64")
# Location Resolution Status
df["Location Resolution Status"] = df["Location Resolution Status"].str.strip()

# Resolve only unique municipality-consistent exact normalized-name matches.
reference = pd.read_parquet(
    facility_reference,
    columns=["Facility Name", "Address", "Latitude", "Longitude"],
)
coordinate_lookup: dict[tuple[str, str], tuple[float, float]] = {}
for municipality in df["Municipality"].astype("string").dropna().unique():
    candidates = reference[
        reference["Address"].astype("string").str.contains(
            municipality, regex=False, na=False
        )
    ].copy()
    candidates["_normalized_name"] = candidates["Facility Name"].map(
        normalize_facility_name
    )
    unique_names = candidates["_normalized_name"].value_counts()
    candidates = candidates[
        candidates["_normalized_name"].map(unique_names).eq(1)
    ]
    for _, row in candidates.iterrows():
        coordinate_lookup[(municipality, row["_normalized_name"])] = (
            float(row["Latitude"]),
            float(row["Longitude"]),
        )

lookup_keys = [
    (municipality, normalize_facility_name(name))
    for municipality, name in zip(
        df["Municipality"].astype("string"), df["Water Point Name"]
    )
]
matched_coordinates = pd.Series(
    [coordinate_lookup.get(key) for key in lookup_keys], index=df.index
)
matched = matched_coordinates.notna()
df.loc[matched, "Latitude"] = matched_coordinates[matched].map(lambda pair: pair[0])
df.loc[matched, "Longitude"] = matched_coordinates[matched].map(lambda pair: pair[1])
df["Location Resolution Status"] = pd.Series(
    "unmatched", index=df.index, dtype="string"
)
df.loc[matched, "Location Resolution Status"] = "matched_exact_2012_facility"
df["Location Resolution Status"] = df["Location Resolution Status"].astype("category")

# --- Save ---
dst.parent.mkdir(parents=True, exist_ok=True)
df.to_parquet(dst, index=False, engine="pyarrow")
print(f"Saved {len(df):,} rows × {len(df.columns)} cols → {dst.relative_to(ROOT)}")
