#!/usr/bin/env python3
"""Preprocessing script for data/raw/2026_kumamoto_earthquake/extracted/shelters_current.csv
Output: data/processed/shelters_current_preprocessed.parquet

Generated by data-preprocessing skill.
"""
from __future__ import annotations

import re
import unicodedata

import pandas as pd
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]  # project root

src = ROOT / "data/raw/2026_kumamoto_earthquake/extracted/shelters_current.csv"
dst = ROOT / "data/processed/shelters_current_preprocessed.parquet"
facility_reference = (
    ROOT.parent
    / "KE01b/data/processed/kumamoto_evacuation_facilities_2012_preprocessed.parquet"
)


def normalize_facility_name(value: object) -> str:
    """Normalize Japanese facility names without applying fuzzy matching."""
    normalized = unicodedata.normalize("NFKC", str(value))
    normalized = re.sub(r"[\s　・･()（）]", "", normalized)
    return normalized.replace("コミセン", "コミュニティセンター")

# --- Load ---
df = pd.read_csv(src, encoding="utf-8-sig", low_memory=False)

# --- Select and rename columns ---
rename_map = {
    "municipality": "Municipality",
    "shelter_number": "Shelter Number",
    "shelter_name": "Shelter Name",
    "district": "District",
    "maximum_capacity": "Maximum Capacity",
    "evacuee_households": "Evacuee Households",
    "evacuee_people": "Evacuee People",
    "water_status_symbol": "Water Status",
    "electricity_status_symbol": "Electricity Status",
    "air_conditioning_status_symbol": "Air Conditioning Status",
    "toilet_count": "Toilet Count",
    "portable_toilet_count": "Portable Toilet Count",
    "snapshot_time": "Snapshot Time",
    "source_url": "Source URL",
    "source_file": "Source File",
    "source_retrieved_at_utc": "Source Retrieved At UTC",
    "latitude": "Latitude",
    "longitude": "Longitude",
    "location_resolution_status": "Location Resolution Status",
}
df = df[list(rename_map.keys())].rename(columns=rename_map)

# --- Variable-level preprocessing ---
# Municipality
df["Municipality"] = df["Municipality"].str.strip()
df["Municipality"] = df["Municipality"].astype("category")
# Shelter Number
df["Shelter Number"] = pd.to_numeric(df["Shelter Number"], errors="coerce")
df["Shelter Number"] = df["Shelter Number"].astype("Int64")
# Shelter Name
df["Shelter Name"] = df["Shelter Name"].str.strip()
# District
df["District"] = df["District"].str.strip()
df["District"] = df["District"].astype("category")
# Maximum Capacity
df["Maximum Capacity"] = pd.to_numeric(df["Maximum Capacity"], errors="coerce")
df["Maximum Capacity"] = df["Maximum Capacity"].astype("Int64")
# Evacuee Households
df["Evacuee Households"] = pd.to_numeric(df["Evacuee Households"], errors="coerce")
df["Evacuee Households"] = df["Evacuee Households"].astype("Int64")
# Evacuee People
df["Evacuee People"] = pd.to_numeric(df["Evacuee People"], errors="coerce")
df["Evacuee People"] = df["Evacuee People"].astype("Int64")
# Water Status
df["Water Status"] = df["Water Status"].str.strip()
df["Water Status"] = df["Water Status"].map(
    {"○": "available", "△": "partially available", "×": "unavailable"}
)
df["Water Status"] = df["Water Status"].astype("category")
# Electricity Status
df["Electricity Status"] = df["Electricity Status"].str.strip()
df["Electricity Status"] = df["Electricity Status"].map(
    {"○": "available", "△": "partially available", "×": "unavailable"}
)
df["Electricity Status"] = df["Electricity Status"].astype("category")
# Air Conditioning Status
df["Air Conditioning Status"] = df["Air Conditioning Status"].str.strip()
df["Air Conditioning Status"] = df["Air Conditioning Status"].map(
    {"○": "available", "△": "partially available", "×": "unavailable"}
)
df["Air Conditioning Status"] = df["Air Conditioning Status"].astype("category")
# Toilet Count
df["Toilet Count"] = pd.to_numeric(df["Toilet Count"], errors="coerce")
df["Toilet Count"] = df["Toilet Count"].astype("Int64")
# Portable Toilet Count
df["Portable Toilet Count"] = pd.to_numeric(df["Portable Toilet Count"], errors="coerce")
df["Portable Toilet Count"] = df["Portable Toilet Count"].astype("Int64")
# Snapshot Time
df["Snapshot Time"] = pd.to_datetime(
    df["Snapshot Time"], errors="coerce", utc=True
).dt.tz_convert("Asia/Tokyo")
# Source URL
df["Source URL"] = df["Source URL"].str.strip()
# Source File
df["Source File"] = df["Source File"].str.strip()
# Source Retrieved At UTC
df["Source Retrieved At UTC"] = pd.to_datetime(
    df["Source Retrieved At UTC"], errors="coerce", utc=True
)
# Latitude
df["Latitude"] = pd.to_numeric(df["Latitude"], errors="coerce")
df["Latitude"] = df["Latitude"].astype("Float64")
# Longitude
df["Longitude"] = pd.to_numeric(df["Longitude"], errors="coerce")
df["Longitude"] = df["Longitude"].astype("Float64")
# Location Resolution Status
df["Location Resolution Status"] = df["Location Resolution Status"].str.strip()

# Resolve only unique municipality-consistent exact normalized-name matches.
reference = pd.read_parquet(
    facility_reference,
    columns=["Facility Name", "Address", "Latitude", "Longitude"],
)
coordinate_lookup: dict[tuple[str, str], tuple[float, float]] = {}
for municipality in df["Municipality"].astype("string").dropna().unique():
    candidates = reference[
        reference["Address"].astype("string").str.contains(
            municipality, regex=False, na=False
        )
    ].copy()
    candidates["_normalized_name"] = candidates["Facility Name"].map(
        normalize_facility_name
    )
    unique_names = candidates["_normalized_name"].value_counts()
    candidates = candidates[
        candidates["_normalized_name"].map(unique_names).eq(1)
    ]
    for _, row in candidates.iterrows():
        coordinate_lookup[(municipality, row["_normalized_name"])] = (
            float(row["Latitude"]),
            float(row["Longitude"]),
        )

lookup_keys = [
    (municipality, normalize_facility_name(name))
    for municipality, name in zip(
        df["Municipality"].astype("string"), df["Shelter Name"]
    )
]
matched_coordinates = pd.Series(
    [coordinate_lookup.get(key) for key in lookup_keys], index=df.index
)
matched = matched_coordinates.notna()
df.loc[matched, "Latitude"] = matched_coordinates[matched].map(lambda pair: pair[0])
df.loc[matched, "Longitude"] = matched_coordinates[matched].map(lambda pair: pair[1])
df["Location Resolution Status"] = pd.Series(
    "unmatched", index=df.index, dtype="string"
)
df.loc[matched, "Location Resolution Status"] = "matched_exact_2012_facility"
df["Location Resolution Status"] = df["Location Resolution Status"].astype("category")

# --- Save ---
dst.parent.mkdir(parents=True, exist_ok=True)
df.to_parquet(dst, index=False, engine="pyarrow")
print(f"Saved {len(df):,} rows × {len(df.columns)} cols → {dst.relative_to(ROOT)}")
