#!/usr/bin/env python3
"""Preprocessing script for data/raw/2026_kumamoto_earthquake/extracted/outage_tanker_snapshots.csv
Output: data/processed/outage_tanker_snapshots_preprocessed.parquet

Generated by data-preprocessing skill.
"""
from __future__ import annotations

import pandas as pd
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]  # project root

src = ROOT / "data/raw/2026_kumamoto_earthquake/extracted/outage_tanker_snapshots.csv"
dst = ROOT / "data/processed/outage_tanker_snapshots_preprocessed.parquet"

# --- Load ---
df = pd.read_csv(src, encoding="utf-8-sig", low_memory=False)

# --- Select and rename columns ---
rename_map = {
    "report_number": "Report Number",
    "report_timestamp": "Report Timestamp",
    "water_status_timestamp": "Water Status Timestamp",
    "reporting_unit_type": "Reporting Unit Type",
    "reporting_unit": "Reporting Unit",
    "maximum_outage_households": "Maximum Outage Households",
    "current_outage_households": "Current Outage Households",
    "outage_period_text": "Outage Period",
    "damage_status_text": "Damage Status",
    "tanker_total": "Tanker Total",
    "tanker_mlit": "MLIT Tankers",
    "tanker_jwwa": "JWWA Tankers",
    "tanker_sdf": "SDF Tankers",
    "tanker_parse_status": "Tanker Parse Status",
    "outage_raw_line": "Outage Raw Text",
    "tanker_raw_line": "Tanker Raw Text",
    "source_url": "Source URL",
    "source_file": "Source File",
    "source_retrieved_at_utc": "Source Retrieved At UTC",
}
df = df[list(rename_map.keys())].rename(columns=rename_map)

# --- Variable-level preprocessing ---
# Report Number
df["Report Number"] = pd.to_numeric(df["Report Number"], errors="coerce")
df["Report Number"] = df["Report Number"].astype("Int64")
# Report Timestamp
df["Report Timestamp"] = pd.to_datetime(
    df["Report Timestamp"], errors="coerce", utc=True
).dt.tz_convert("Asia/Tokyo")
# Water Status Timestamp
df["Water Status Timestamp"] = pd.to_datetime(
    df["Water Status Timestamp"], errors="coerce", utc=True
).dt.tz_convert("Asia/Tokyo")
# Reporting Unit Type
df["Reporting Unit Type"] = df["Reporting Unit Type"].str.strip()
df["Reporting Unit Type"] = df["Reporting Unit Type"].astype("category")
# Reporting Unit
df["Reporting Unit"] = df["Reporting Unit"].str.strip()
df["Reporting Unit"] = df["Reporting Unit"].astype("category")
# Maximum Outage Households
df["Maximum Outage Households"] = pd.to_numeric(df["Maximum Outage Households"], errors="coerce")
df["Maximum Outage Households"] = df["Maximum Outage Households"].astype("Int64")
# Current Outage Households
df["Current Outage Households"] = pd.to_numeric(df["Current Outage Households"], errors="coerce")
df["Current Outage Households"] = df["Current Outage Households"].astype("Int64")
# Outage Period
df["Outage Period"] = df["Outage Period"].str.strip()
# Damage Status
df["Damage Status"] = df["Damage Status"].str.strip()
# Tanker Total
df["Tanker Total"] = pd.to_numeric(df["Tanker Total"], errors="coerce")
df["Tanker Total"] = df["Tanker Total"].astype("Int64")
# MLIT Tankers
df["MLIT Tankers"] = pd.to_numeric(df["MLIT Tankers"], errors="coerce")
df["MLIT Tankers"] = df["MLIT Tankers"].astype("Int64")
# JWWA Tankers
df["JWWA Tankers"] = pd.to_numeric(df["JWWA Tankers"], errors="coerce")
df["JWWA Tankers"] = df["JWWA Tankers"].astype("Int64")
# SDF Tankers
df["SDF Tankers"] = pd.to_numeric(df["SDF Tankers"], errors="coerce")
df["SDF Tankers"] = df["SDF Tankers"].astype("Int64")
# Tanker Parse Status
df["Tanker Parse Status"] = df["Tanker Parse Status"].str.strip()
df["Tanker Parse Status"] = df["Tanker Parse Status"].astype("category")
# Outage Raw Text
df["Outage Raw Text"] = df["Outage Raw Text"].str.strip()
# Tanker Raw Text
df["Tanker Raw Text"] = df["Tanker Raw Text"].str.strip()
# Source URL
df["Source URL"] = df["Source URL"].str.strip()
# Source File
df["Source File"] = df["Source File"].str.strip()
# Source Retrieved At UTC
df["Source Retrieved At UTC"] = pd.to_datetime(
    df["Source Retrieved At UTC"], errors="coerce", utc=True
)

# --- Save ---
dst.parent.mkdir(parents=True, exist_ok=True)
df.to_parquet(dst, index=False, engine="pyarrow")
print(f"Saved {len(df):,} rows × {len(df.columns)} cols → {dst.relative_to(ROOT)}")
